name: Azure Family To-Do App CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Azure CLI
        uses: azure/cli@v2

      - name: Set up azd
        uses: Azure/azure-dev@v1

      - name: azd login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: azd provision
        run: azd provision

      - name: azd deploy
        run: azd deploy

      - name: Get PostgreSQL password from Key Vault
        id: get-pgpass
        uses: azure/cli@v2
        with:
          inlineScript: |
            export PGPASSWORD=$(az keyvault secret show --vault-name ${{ env.AZURE_KEYVAULT_NAME }} --name postgres-password --query value -o tsv)
            echo "::add-mask::$PGPASSWORD"
            echo "PGPASSWORD=$PGPASSWORD" >> $GITHUB_ENV

      - name: Run DB schema migration
        env:
          PGPASSWORD: ${{ env.PGPASSWORD }}
        run: |
          psql "host=${{ env.POSTGRES_HOST }} dbname=${{ env.POSTGRES_DB }} user=${{ env.POSTGRES_USER }} password=${{ env.PGPASSWORD }} sslmode=require" -f src/api/db_schema.sql
