name: Azure Developer CLI CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment to deploy to.'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - test
          - staging

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'dev' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Set up Azure CLI
        uses: azure/cli@v2
        with:
          inlineScript: |
            az --version

      - name: Set up azd
        uses: Azure/setup-azd@v2

      - name: Log in to Azure (OIDC)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Authenticate with azd (OIDC)
        run: |
          azd auth login --client-id ${{ secrets.AZURE_CLIENT_ID }} --tenant-id ${{ secrets.AZURE_TENANT_ID }} --federated-credential-provider github

      - name: Create or Update azd environment
        run: |
          azd env new ${{ github.event.inputs.environment || 'dev' }} --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }} --location ${{ secrets.AZURE_LOCATION }} --no-prompt

      - name: Provision Infrastructure
        run: |
          azd provision --environment ${{ github.event.inputs.environment || 'dev' }} --no-prompt

      - name: Deploy Application
        run: |
          azd deploy --environment ${{ github.event.inputs.environment || 'dev' }} --no-prompt